<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure\lbsnOrigin;

use UnexpectedValueException;

/**
 * A unique identifier of the object.
 *
 * Protobuf type <code>lbsn.structure.lbsnOrigin.OriginID</code>
 */
class OriginID
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>INSTAGRAM = 1;</code>
     */
    const INSTAGRAM = 1;
    /**
     * Generated from protobuf enum <code>FLICKR = 2;</code>
     */
    const FLICKR = 2;
    /**
     * Generated from protobuf enum <code>TWITTER = 3;</code>
     */
    const TWITTER = 3;
    /**
     * Generated from protobuf enum <code>FACEBOOK = 4;</code>
     */
    const FACEBOOK = 4;
    /**
     * Generated from protobuf enum <code>FOURSQUARE = 5;</code>
     */
    const FOURSQUARE = 5;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::INSTAGRAM => 'INSTAGRAM',
        self::FLICKR => 'FLICKR',
        self::TWITTER => 'TWITTER',
        self::FACEBOOK => 'FACEBOOK',
        self::FOURSQUARE => 'FOURSQUARE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OriginID::class, \Lbsn\Structure\lbsnOrigin_OriginID::class);

