<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

if (false) {
    /**
     * This class is deprecated. Use lbsnOrigin\OriginID instead.
     * @deprecated
     */
    class lbsnOrigin_OriginID {}
}
class_exists(lbsnOrigin\OriginID::class);
@trigger_error('lbsnOrigin_OriginID is deprecated and will be removed in the next major release. Use lbsnOrigin\OriginID instead', E_USER_DEPRECATED);

