<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

if (false) {
    /**
     * This class is deprecated. Use lbsnPost\PostGeoaccuracy instead.
     * @deprecated
     */
    class lbsnPost_PostGeoaccuracy {}
}
class_exists(lbsnPost\PostGeoaccuracy::class);
@trigger_error('lbsnPost_PostGeoaccuracy is deprecated and will be removed in the next major release. Use lbsnPost\PostGeoaccuracy instead', E_USER_DEPRECATED);

