<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Language</code>
 */
final class Language extends \Google\Protobuf\Internal\Message
{
    /**
     * Primary Key. A unique identifier of the object.
     * A BCP 47 language identifier corresponding to the (machine-detected language) of the Post body-text, empty/whitespace if no language could be detected, NULL if not specified.
     *
     * Generated from protobuf field <code>string language_short = 1;</code>
     */
    private $language_short = '';
    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string language_name_de = 3;</code>
     */
    private $language_name_de = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $language_short
     *           Primary Key. A unique identifier of the object.
     *           A BCP 47 language identifier corresponding to the (machine-detected language) of the Post body-text, empty/whitespace if no language could be detected, NULL if not specified.
     *     @type string $name
     *           Optional Attributes
     *     @type string $language_name_de
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lbsnstructure\Lbsnstructure::initOnce();
        parent::__construct($data);
    }

    /**
     * Primary Key. A unique identifier of the object.
     * A BCP 47 language identifier corresponding to the (machine-detected language) of the Post body-text, empty/whitespace if no language could be detected, NULL if not specified.
     *
     * Generated from protobuf field <code>string language_short = 1;</code>
     * @return string
     */
    public function getLanguageShort()
    {
        return $this->language_short;
    }

    /**
     * Primary Key. A unique identifier of the object.
     * A BCP 47 language identifier corresponding to the (machine-detected language) of the Post body-text, empty/whitespace if no language could be detected, NULL if not specified.
     *
     * Generated from protobuf field <code>string language_short = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageShort($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_short = $var;

        return $this;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language_name_de = 3;</code>
     * @return string
     */
    public function getLanguageNameDe()
    {
        return $this->language_name_de;
    }

    /**
     * Generated from protobuf field <code>string language_name_de = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageNameDe($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_name_de = $var;

        return $this;
    }

}

