<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

if (false) {
    /**
     * This class is deprecated. Use lbsnRelationship\RelationshipType instead.
     * @deprecated
     */
    class lbsnRelationship_RelationshipType {}
}
class_exists(lbsnRelationship\RelationshipType::class);
@trigger_error('lbsnRelationship_RelationshipType is deprecated and will be removed in the next major release. Use lbsnRelationship\RelationshipType instead', E_USER_DEPRECATED);

