<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

if (false) {
    /**
     * This class is deprecated. Use lbsnPostReaction\ReactionType instead.
     * @deprecated
     */
    class lbsnPostReaction_ReactionType {}
}
class_exists(lbsnPostReaction\ReactionType::class);
@trigger_error('lbsnPostReaction_ReactionType is deprecated and will be removed in the next major release. Use lbsnPostReaction\ReactionType instead', E_USER_DEPRECATED);

