<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

if (false) {
    /**
     * This class is deprecated. Use lbsnPost\PostType instead.
     * @deprecated
     */
    class lbsnPost_PostType {}
}
class_exists(lbsnPost\PostType::class);
@trigger_error('lbsnPost_PostType is deprecated and will be removed in the next major release. Use lbsnPost\PostType instead', E_USER_DEPRECATED);

