<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lbsnUser</code>
 */
final class lbsnUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.CompositeKey pkey = 1;</code>
     */
    private $pkey = null;
    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string user_name = 2;</code>
     */
    private $user_name = '';
    /**
     * Generated from protobuf field <code>string user_fullname = 3;</code>
     */
    private $user_fullname = '';
    /**
     * Generated from protobuf field <code>int64 follows = 4;</code>
     */
    private $follows = 0;
    /**
     * Generated from protobuf field <code>int64 followed = 5;</code>
     */
    private $followed = 0;
    /**
     *The number of public groups or communities this user is part of
     *
     * Generated from protobuf field <code>int64 group_count = 6;</code>
     */
    private $group_count = 0;
    /**
     * Generated from protobuf field <code>string biography = 7;</code>
     */
    private $biography = '';
    /**
     * Generated from protobuf field <code>int64 post_count = 8;</code>
     */
    private $post_count = 0;
    /**
     * Generated from protobuf field <code>string url = 9;</code>
     */
    private $url = '';
    /**
     * Generated from protobuf field <code>bool is_private = 10;</code>
     */
    private $is_private = false;
    /**
     * Generated from protobuf field <code>bool is_available = 11;</code>
     */
    private $is_available = false;
    /**
     * Generated from protobuf field <code>.Language user_language = 12;</code>
     */
    private $user_language = null;
    /**
     *The user-defined location for this profile. Not necessarily a location, nor machine-parseable.  
     *
     * Generated from protobuf field <code>string user_location = 13;</code>
     */
    private $user_location = '';
    /**
     *(WKT: Point) Coordinates (lat/lng) of the user-location, either provided by user or geocoded from user_location_name.
     *
     * Generated from protobuf field <code>string user_location_geom = 14;</code>
     */
    private $user_location_geom = '';
    /**
     *The number of Posts this user has liked in total.
     *
     * Generated from protobuf field <code>int64 liked_count = 15;</code>
     */
    private $liked_count = 0;
    /**
     *UTC datetime when the user was first active (e.g. time of account creation, or derived from first post_publish_date)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp active_since = 16;</code>
     */
    private $active_since = null;
    /**
     *URL pointing to the profile image of the user.
     *
     * Generated from protobuf field <code>string profile_image_url = 17;</code>
     */
    private $profile_image_url = '';
    /**
     * Generated from protobuf field <code>string user_timezone = 18;</code>
     */
    private $user_timezone = '';
    /**
     * Generated from protobuf field <code>sint32 user_utc_offset = 19;</code>
     */
    private $user_utc_offset = 0;
    /**
     *The list of groups this user has joined/ is a member of (active participation interest).
     *
     * Generated from protobuf field <code>repeated string user_groups_member = 20;</code>
     */
    private $user_groups_member;
    /**
     *The list of groups this user follows (viewing interest).
     *
     * Generated from protobuf field <code>repeated string user_groups_follows = 21;</code>
     */
    private $user_groups_follows;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CompositeKey $pkey
     *           Primary Key. A unique identifier of the object.
     *     @type string $user_name
     *           Optional Attributes
     *     @type string $user_fullname
     *     @type int|string $follows
     *     @type int|string $followed
     *     @type int|string $group_count
     *          The number of public groups or communities this user is part of
     *     @type string $biography
     *     @type int|string $post_count
     *     @type string $url
     *     @type bool $is_private
     *     @type bool $is_available
     *     @type \Language $user_language
     *     @type string $user_location
     *          The user-defined location for this profile. Not necessarily a location, nor machine-parseable.  
     *     @type string $user_location_geom
     *          (WKT: Point) Coordinates (lat/lng) of the user-location, either provided by user or geocoded from user_location_name.
     *     @type int|string $liked_count
     *          The number of Posts this user has liked in total.
     *     @type \Google\Protobuf\Timestamp $active_since
     *          UTC datetime when the user was first active (e.g. time of account creation, or derived from first post_publish_date)
     *     @type string $profile_image_url
     *          URL pointing to the profile image of the user.
     *     @type string $user_timezone
     *     @type int $user_utc_offset
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $user_groups_member
     *          The list of groups this user has joined/ is a member of (active participation interest).
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $user_groups_follows
     *          The list of groups this user follows (viewing interest).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lbsnstructure\Lbsnstructure::initOnce();
        parent::__construct($data);
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.CompositeKey pkey = 1;</code>
     * @return \CompositeKey
     */
    public function getPkey()
    {
        return $this->pkey;
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.CompositeKey pkey = 1;</code>
     * @param \CompositeKey $var
     * @return $this
     */
    public function setPkey($var)
    {
        GPBUtil::checkMessage($var, \CompositeKey::class);
        $this->pkey = $var;

        return $this;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string user_name = 2;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string user_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_fullname = 3;</code>
     * @return string
     */
    public function getUserFullname()
    {
        return $this->user_fullname;
    }

    /**
     * Generated from protobuf field <code>string user_fullname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_fullname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 follows = 4;</code>
     * @return int|string
     */
    public function getFollows()
    {
        return $this->follows;
    }

    /**
     * Generated from protobuf field <code>int64 follows = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFollows($var)
    {
        GPBUtil::checkInt64($var);
        $this->follows = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 followed = 5;</code>
     * @return int|string
     */
    public function getFollowed()
    {
        return $this->followed;
    }

    /**
     * Generated from protobuf field <code>int64 followed = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFollowed($var)
    {
        GPBUtil::checkInt64($var);
        $this->followed = $var;

        return $this;
    }

    /**
     *The number of public groups or communities this user is part of
     *
     * Generated from protobuf field <code>int64 group_count = 6;</code>
     * @return int|string
     */
    public function getGroupCount()
    {
        return $this->group_count;
    }

    /**
     *The number of public groups or communities this user is part of
     *
     * Generated from protobuf field <code>int64 group_count = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string biography = 7;</code>
     * @return string
     */
    public function getBiography()
    {
        return $this->biography;
    }

    /**
     * Generated from protobuf field <code>string biography = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setBiography($var)
    {
        GPBUtil::checkString($var, True);
        $this->biography = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 post_count = 8;</code>
     * @return int|string
     */
    public function getPostCount()
    {
        return $this->post_count;
    }

    /**
     * Generated from protobuf field <code>int64 post_count = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPostCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->post_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 9;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_private = 10;</code>
     * @return bool
     */
    public function getIsPrivate()
    {
        return $this->is_private;
    }

    /**
     * Generated from protobuf field <code>bool is_private = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPrivate($var)
    {
        GPBUtil::checkBool($var);
        $this->is_private = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_available = 11;</code>
     * @return bool
     */
    public function getIsAvailable()
    {
        return $this->is_available;
    }

    /**
     * Generated from protobuf field <code>bool is_available = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAvailable($var)
    {
        GPBUtil::checkBool($var);
        $this->is_available = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Language user_language = 12;</code>
     * @return \Language
     */
    public function getUserLanguage()
    {
        return $this->user_language;
    }

    /**
     * Generated from protobuf field <code>.Language user_language = 12;</code>
     * @param \Language $var
     * @return $this
     */
    public function setUserLanguage($var)
    {
        GPBUtil::checkMessage($var, \Language::class);
        $this->user_language = $var;

        return $this;
    }

    /**
     *The user-defined location for this profile. Not necessarily a location, nor machine-parseable.  
     *
     * Generated from protobuf field <code>string user_location = 13;</code>
     * @return string
     */
    public function getUserLocation()
    {
        return $this->user_location;
    }

    /**
     *The user-defined location for this profile. Not necessarily a location, nor machine-parseable.  
     *
     * Generated from protobuf field <code>string user_location = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setUserLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_location = $var;

        return $this;
    }

    /**
     *(WKT: Point) Coordinates (lat/lng) of the user-location, either provided by user or geocoded from user_location_name.
     *
     * Generated from protobuf field <code>string user_location_geom = 14;</code>
     * @return string
     */
    public function getUserLocationGeom()
    {
        return $this->user_location_geom;
    }

    /**
     *(WKT: Point) Coordinates (lat/lng) of the user-location, either provided by user or geocoded from user_location_name.
     *
     * Generated from protobuf field <code>string user_location_geom = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setUserLocationGeom($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_location_geom = $var;

        return $this;
    }

    /**
     *The number of Posts this user has liked in total.
     *
     * Generated from protobuf field <code>int64 liked_count = 15;</code>
     * @return int|string
     */
    public function getLikedCount()
    {
        return $this->liked_count;
    }

    /**
     *The number of Posts this user has liked in total.
     *
     * Generated from protobuf field <code>int64 liked_count = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLikedCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->liked_count = $var;

        return $this;
    }

    /**
     *UTC datetime when the user was first active (e.g. time of account creation, or derived from first post_publish_date)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp active_since = 16;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getActiveSince()
    {
        return $this->active_since;
    }

    /**
     *UTC datetime when the user was first active (e.g. time of account creation, or derived from first post_publish_date)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp active_since = 16;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setActiveSince($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->active_since = $var;

        return $this;
    }

    /**
     *URL pointing to the profile image of the user.
     *
     * Generated from protobuf field <code>string profile_image_url = 17;</code>
     * @return string
     */
    public function getProfileImageUrl()
    {
        return $this->profile_image_url;
    }

    /**
     *URL pointing to the profile image of the user.
     *
     * Generated from protobuf field <code>string profile_image_url = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_image_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_timezone = 18;</code>
     * @return string
     */
    public function getUserTimezone()
    {
        return $this->user_timezone;
    }

    /**
     * Generated from protobuf field <code>string user_timezone = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setUserTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_timezone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 user_utc_offset = 19;</code>
     * @return int
     */
    public function getUserUtcOffset()
    {
        return $this->user_utc_offset;
    }

    /**
     * Generated from protobuf field <code>sint32 user_utc_offset = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setUserUtcOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_utc_offset = $var;

        return $this;
    }

    /**
     *The list of groups this user has joined/ is a member of (active participation interest).
     *
     * Generated from protobuf field <code>repeated string user_groups_member = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserGroupsMember()
    {
        return $this->user_groups_member;
    }

    /**
     *The list of groups this user has joined/ is a member of (active participation interest).
     *
     * Generated from protobuf field <code>repeated string user_groups_member = 20;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserGroupsMember($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_groups_member = $arr;

        return $this;
    }

    /**
     *The list of groups this user follows (viewing interest).
     *
     * Generated from protobuf field <code>repeated string user_groups_follows = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserGroupsFollows()
    {
        return $this->user_groups_follows;
    }

    /**
     *The list of groups this user follows (viewing interest).
     *
     * Generated from protobuf field <code>repeated string user_groups_follows = 21;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserGroupsFollows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_groups_follows = $arr;

        return $this;
    }

}

