<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lbsnCity</code>
 */
final class lbsnCity extends \Google\Protobuf\Internal\Message
{
    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.CompositeKey pkey = 1;</code>
     */
    private $pkey = null;
    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     *Alternative names (e.g. in other languages; synonyms).
     *
     * Generated from protobuf field <code>repeated string name_alternatives = 3;</code>
     */
    private $name_alternatives;
    /**
     *Subtype for lbsnCity (e.g. "Neighborhood", "Admin", etc.)
     *
     * Generated from protobuf field <code>string sub_type = 4;</code>
     */
    private $sub_type = '';
    /**
     * Generated from protobuf field <code>string url = 5;</code>
     */
    private $url = '';
    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string geom_center = 6;</code>
     */
    private $geom_center = '';
    /**
     *WKT Polygon
     *
     * Generated from protobuf field <code>string geom_area = 7;</code>
     */
    private $geom_area = '';
    /**
     * Generated from protobuf field <code>.CompositeKey country_pkey = 8;</code>
     */
    private $country_pkey = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CompositeKey $pkey
     *           Primary Key. A unique identifier of the object.
     *     @type string $name
     *           Optional Attributes
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $name_alternatives
     *          Alternative names (e.g. in other languages; synonyms).
     *     @type string $sub_type
     *          Subtype for lbsnCity (e.g. "Neighborhood", "Admin", etc.)
     *     @type string $url
     *     @type string $geom_center
     *          WKT Point
     *     @type string $geom_area
     *          WKT Polygon
     *     @type \CompositeKey $country_pkey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lbsnstructure\Lbsnstructure::initOnce();
        parent::__construct($data);
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.CompositeKey pkey = 1;</code>
     * @return \CompositeKey
     */
    public function getPkey()
    {
        return $this->pkey;
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.CompositeKey pkey = 1;</code>
     * @param \CompositeKey $var
     * @return $this
     */
    public function setPkey($var)
    {
        GPBUtil::checkMessage($var, \CompositeKey::class);
        $this->pkey = $var;

        return $this;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *Alternative names (e.g. in other languages; synonyms).
     *
     * Generated from protobuf field <code>repeated string name_alternatives = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNameAlternatives()
    {
        return $this->name_alternatives;
    }

    /**
     *Alternative names (e.g. in other languages; synonyms).
     *
     * Generated from protobuf field <code>repeated string name_alternatives = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNameAlternatives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->name_alternatives = $arr;

        return $this;
    }

    /**
     *Subtype for lbsnCity (e.g. "Neighborhood", "Admin", etc.)
     *
     * Generated from protobuf field <code>string sub_type = 4;</code>
     * @return string
     */
    public function getSubType()
    {
        return $this->sub_type;
    }

    /**
     *Subtype for lbsnCity (e.g. "Neighborhood", "Admin", etc.)
     *
     * Generated from protobuf field <code>string sub_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubType($var)
    {
        GPBUtil::checkString($var, True);
        $this->sub_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 5;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string geom_center = 6;</code>
     * @return string
     */
    public function getGeomCenter()
    {
        return $this->geom_center;
    }

    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string geom_center = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setGeomCenter($var)
    {
        GPBUtil::checkString($var, True);
        $this->geom_center = $var;

        return $this;
    }

    /**
     *WKT Polygon
     *
     * Generated from protobuf field <code>string geom_area = 7;</code>
     * @return string
     */
    public function getGeomArea()
    {
        return $this->geom_area;
    }

    /**
     *WKT Polygon
     *
     * Generated from protobuf field <code>string geom_area = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setGeomArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->geom_area = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CompositeKey country_pkey = 8;</code>
     * @return \CompositeKey
     */
    public function getCountryPkey()
    {
        return $this->country_pkey;
    }

    /**
     * Generated from protobuf field <code>.CompositeKey country_pkey = 8;</code>
     * @param \CompositeKey $var
     * @return $this
     */
    public function setCountryPkey($var)
    {
        GPBUtil::checkMessage($var, \CompositeKey::class);
        $this->country_pkey = $var;

        return $this;
    }

}

