<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

if (false) {
    /**
     * This class is deprecated. Use Lbsn\Structure\lbsnPost\PostGeoaccuracy instead.
     * @deprecated
     */
    class lbsnPost_PostGeoaccuracy {}
}
class_exists(lbsnPost\PostGeoaccuracy::class);
@trigger_error('Lbsn\Structure\lbsnPost_PostGeoaccuracy is deprecated and will be removed in the next major release. Use Lbsn\Structure\lbsnPost\PostGeoaccuracy instead', E_USER_DEPRECATED);

