<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

if (false) {
    /**
     * This class is deprecated. Use Lbsn\Structure\lbsnOrigin\OriginID instead.
     * @deprecated
     */
    class lbsnOrigin_OriginID {}
}
class_exists(lbsnOrigin\OriginID::class);
@trigger_error('Lbsn\Structure\lbsnOrigin_OriginID is deprecated and will be removed in the next major release. Use Lbsn\Structure\lbsnOrigin\OriginID instead', E_USER_DEPRECATED);

