<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lbsn.structure.lbsnCountry</code>
 */
final class lbsnCountry extends \Google\Protobuf\Internal\Message
{
    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey pkey = 1;</code>
     */
    private $pkey = null;
    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>repeated string name_alternatives = 3;</code>
     */
    private $name_alternatives;
    /**
     * Generated from protobuf field <code>string url = 4;</code>
     */
    private $url = '';
    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string geom_center = 5;</code>
     */
    private $geom_center = '';
    /**
     *WKT Polygon   
     *
     * Generated from protobuf field <code>string geom_area = 6;</code>
     */
    private $geom_area = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lbsn\Structure\CompositeKey $pkey
     *           Primary Key. A unique identifier of the object.
     *     @type string $name
     *           Optional Attributes
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $name_alternatives
     *     @type string $url
     *     @type string $geom_center
     *          WKT Point
     *     @type string $geom_area
     *          WKT Polygon   
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lbsnstructure\Lbsnstructure::initOnce();
        parent::__construct($data);
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey pkey = 1;</code>
     * @return \Lbsn\Structure\CompositeKey
     */
    public function getPkey()
    {
        return $this->pkey;
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey pkey = 1;</code>
     * @param \Lbsn\Structure\CompositeKey $var
     * @return $this
     */
    public function setPkey($var)
    {
        GPBUtil::checkMessage($var, \Lbsn\Structure\CompositeKey::class);
        $this->pkey = $var;

        return $this;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string name_alternatives = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNameAlternatives()
    {
        return $this->name_alternatives;
    }

    /**
     * Generated from protobuf field <code>repeated string name_alternatives = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNameAlternatives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->name_alternatives = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 4;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string geom_center = 5;</code>
     * @return string
     */
    public function getGeomCenter()
    {
        return $this->geom_center;
    }

    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string geom_center = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGeomCenter($var)
    {
        GPBUtil::checkString($var, True);
        $this->geom_center = $var;

        return $this;
    }

    /**
     *WKT Polygon   
     *
     * Generated from protobuf field <code>string geom_area = 6;</code>
     * @return string
     */
    public function getGeomArea()
    {
        return $this->geom_area;
    }

    /**
     *WKT Polygon   
     *
     * Generated from protobuf field <code>string geom_area = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setGeomArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->geom_area = $var;

        return $this;
    }

}

