<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

if (false) {
    /**
     * This class is deprecated. Use Lbsn\Structure\lbsnPostReaction\ReactionType instead.
     * @deprecated
     */
    class lbsnPostReaction_ReactionType {}
}
class_exists(lbsnPostReaction\ReactionType::class);
@trigger_error('Lbsn\Structure\lbsnPostReaction_ReactionType is deprecated and will be removed in the next major release. Use Lbsn\Structure\lbsnPostReaction\ReactionType instead', E_USER_DEPRECATED);

