<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lbsn.structure.lbsnPostReaction</code>
 */
final class lbsnPostReaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey pkey = 1;</code>
     */
    private $pkey = null;
    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey user_pkey = 2;</code>
     */
    private $user_pkey = null;
    /**
     * a reference to post to which this reaction refers to  (e.g. doe a reaction of type REPLY, reference original post_pkey here)
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey referencedPost_pkey = 3;</code>
     */
    private $referencedPost_pkey = null;
    /**
     * a reference to another reaction (e.g. if this reaction is a "like" of another reaction, reference original postreaction_pkey here)
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey referencedPostreaction_pkey = 4;</code>
     */
    private $referencedPostreaction_pkey = null;
    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string reaction_latlng = 5;</code>
     */
    private $reaction_latlng = '';
    /**
     * Generated from protobuf field <code>.lbsn.structure.lbsnPostReaction.ReactionType reaction_type = 6;</code>
     */
    private $reaction_type = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp reaction_date = 7;</code>
     */
    private $reaction_date = null;
    /**
     * Generated from protobuf field <code>string reaction_content = 8;</code>
     */
    private $reaction_content = '';
    /**
     * Generated from protobuf field <code>int64 reaction_like_count = 9;</code>
     */
    private $reaction_like_count = 0;
    /**
     * Generated from protobuf field <code>repeated .lbsn.structure.CompositeKey user_mentions_pkey = 10;</code>
     */
    private $user_mentions_pkey;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lbsn\Structure\CompositeKey $pkey
     *           Primary Key. A unique identifier of the object.
     *     @type \Lbsn\Structure\CompositeKey $user_pkey
     *           Optional Attributes
     *     @type \Lbsn\Structure\CompositeKey $referencedPost_pkey
     *           a reference to post to which this reaction refers to  (e.g. doe a reaction of type REPLY, reference original post_pkey here)
     *     @type \Lbsn\Structure\CompositeKey $referencedPostreaction_pkey
     *           a reference to another reaction (e.g. if this reaction is a "like" of another reaction, reference original postreaction_pkey here)
     *     @type string $reaction_latlng
     *          WKT Point
     *     @type int $reaction_type
     *     @type \Google\Protobuf\Timestamp $reaction_date
     *     @type string $reaction_content
     *     @type int|string $reaction_like_count
     *     @type \Lbsn\Structure\CompositeKey[]|\Google\Protobuf\Internal\RepeatedField $user_mentions_pkey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lbsnstructure\Lbsnstructure::initOnce();
        parent::__construct($data);
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey pkey = 1;</code>
     * @return \Lbsn\Structure\CompositeKey
     */
    public function getPkey()
    {
        return $this->pkey;
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey pkey = 1;</code>
     * @param \Lbsn\Structure\CompositeKey $var
     * @return $this
     */
    public function setPkey($var)
    {
        GPBUtil::checkMessage($var, \Lbsn\Structure\CompositeKey::class);
        $this->pkey = $var;

        return $this;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey user_pkey = 2;</code>
     * @return \Lbsn\Structure\CompositeKey
     */
    public function getUserPkey()
    {
        return $this->user_pkey;
    }

    /**
     * Optional Attributes
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey user_pkey = 2;</code>
     * @param \Lbsn\Structure\CompositeKey $var
     * @return $this
     */
    public function setUserPkey($var)
    {
        GPBUtil::checkMessage($var, \Lbsn\Structure\CompositeKey::class);
        $this->user_pkey = $var;

        return $this;
    }

    /**
     * a reference to post to which this reaction refers to  (e.g. doe a reaction of type REPLY, reference original post_pkey here)
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey referencedPost_pkey = 3;</code>
     * @return \Lbsn\Structure\CompositeKey
     */
    public function getReferencedPostPkey()
    {
        return $this->referencedPost_pkey;
    }

    /**
     * a reference to post to which this reaction refers to  (e.g. doe a reaction of type REPLY, reference original post_pkey here)
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey referencedPost_pkey = 3;</code>
     * @param \Lbsn\Structure\CompositeKey $var
     * @return $this
     */
    public function setReferencedPostPkey($var)
    {
        GPBUtil::checkMessage($var, \Lbsn\Structure\CompositeKey::class);
        $this->referencedPost_pkey = $var;

        return $this;
    }

    /**
     * a reference to another reaction (e.g. if this reaction is a "like" of another reaction, reference original postreaction_pkey here)
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey referencedPostreaction_pkey = 4;</code>
     * @return \Lbsn\Structure\CompositeKey
     */
    public function getReferencedPostreactionPkey()
    {
        return $this->referencedPostreaction_pkey;
    }

    /**
     * a reference to another reaction (e.g. if this reaction is a "like" of another reaction, reference original postreaction_pkey here)
     *
     * Generated from protobuf field <code>.lbsn.structure.CompositeKey referencedPostreaction_pkey = 4;</code>
     * @param \Lbsn\Structure\CompositeKey $var
     * @return $this
     */
    public function setReferencedPostreactionPkey($var)
    {
        GPBUtil::checkMessage($var, \Lbsn\Structure\CompositeKey::class);
        $this->referencedPostreaction_pkey = $var;

        return $this;
    }

    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string reaction_latlng = 5;</code>
     * @return string
     */
    public function getReactionLatlng()
    {
        return $this->reaction_latlng;
    }

    /**
     *WKT Point
     *
     * Generated from protobuf field <code>string reaction_latlng = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setReactionLatlng($var)
    {
        GPBUtil::checkString($var, True);
        $this->reaction_latlng = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lbsn.structure.lbsnPostReaction.ReactionType reaction_type = 6;</code>
     * @return int
     */
    public function getReactionType()
    {
        return $this->reaction_type;
    }

    /**
     * Generated from protobuf field <code>.lbsn.structure.lbsnPostReaction.ReactionType reaction_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setReactionType($var)
    {
        GPBUtil::checkEnum($var, \Lbsn\Structure\lbsnPostReaction_ReactionType::class);
        $this->reaction_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp reaction_date = 7;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getReactionDate()
    {
        return $this->reaction_date;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp reaction_date = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setReactionDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->reaction_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reaction_content = 8;</code>
     * @return string
     */
    public function getReactionContent()
    {
        return $this->reaction_content;
    }

    /**
     * Generated from protobuf field <code>string reaction_content = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setReactionContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->reaction_content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reaction_like_count = 9;</code>
     * @return int|string
     */
    public function getReactionLikeCount()
    {
        return $this->reaction_like_count;
    }

    /**
     * Generated from protobuf field <code>int64 reaction_like_count = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReactionLikeCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->reaction_like_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lbsn.structure.CompositeKey user_mentions_pkey = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserMentionsPkey()
    {
        return $this->user_mentions_pkey;
    }

    /**
     * Generated from protobuf field <code>repeated .lbsn.structure.CompositeKey user_mentions_pkey = 10;</code>
     * @param \Lbsn\Structure\CompositeKey[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserMentionsPkey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lbsn\Structure\CompositeKey::class);
        $this->user_mentions_pkey = $arr;

        return $this;
    }

}

