<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

if (false) {
    /**
     * This class is deprecated. Use Lbsn\Structure\Origin\OriginID instead.
     * @deprecated
     */
    class Origin_OriginID {}
}
class_exists(Origin\OriginID::class);
@trigger_error('Lbsn\Structure\Origin_OriginID is deprecated and will be removed in the next major release. Use Lbsn\Structure\Origin\OriginID instead', E_USER_DEPRECATED);

