<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

if (false) {
    /**
     * This class is deprecated. Use Lbsn\Structure\PostReaction\ReactionType instead.
     * @deprecated
     */
    class PostReaction_ReactionType {}
}
class_exists(PostReaction\ReactionType::class);
@trigger_error('Lbsn\Structure\PostReaction_ReactionType is deprecated and will be removed in the next major release. Use Lbsn\Structure\PostReaction\ReactionType instead', E_USER_DEPRECATED);

