<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

if (false) {
    /**
     * This class is deprecated. Use Lbsn\Structure\Post\PostType instead.
     * @deprecated
     */
    class Post_PostType {}
}
class_exists(Post\PostType::class);
@trigger_error('Lbsn\Structure\Post_PostType is deprecated and will be removed in the next major release. Use Lbsn\Structure\Post\PostType instead', E_USER_DEPRECATED);

