<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

if (false) {
    /**
     * This class is deprecated. Use Lbsn\Structure\Relationship\RelationshipType instead.
     * @deprecated
     */
    class Relationship_RelationshipType {}
}
class_exists(Relationship\RelationshipType::class);
@trigger_error('Lbsn\Structure\Relationship_RelationshipType is deprecated and will be removed in the next major release. Use Lbsn\Structure\Relationship\RelationshipType instead', E_USER_DEPRECATED);

