<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/lbsnstructure.proto

namespace Lbsn\Structure;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lbsn.structure.Relationship</code>
 */
final class Relationship extends \Google\Protobuf\Internal\Message
{
    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.RelationshipKey pkey = 1;</code>
     */
    private $pkey = null;
    /**
     * Generated from protobuf field <code>.lbsn.structure.Relationship.RelationshipType relationship_type = 2;</code>
     */
    private $relationship_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lbsn\Structure\RelationshipKey $pkey
     *           Primary Key. A unique identifier of the object.
     *     @type int $relationship_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lbsnstructure\Lbsnstructure::initOnce();
        parent::__construct($data);
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.RelationshipKey pkey = 1;</code>
     * @return \Lbsn\Structure\RelationshipKey
     */
    public function getPkey()
    {
        return $this->pkey;
    }

    /**
     * Primary Key. A unique identifier of the object.
     *
     * Generated from protobuf field <code>.lbsn.structure.RelationshipKey pkey = 1;</code>
     * @param \Lbsn\Structure\RelationshipKey $var
     * @return $this
     */
    public function setPkey($var)
    {
        GPBUtil::checkMessage($var, \Lbsn\Structure\RelationshipKey::class);
        $this->pkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lbsn.structure.Relationship.RelationshipType relationship_type = 2;</code>
     * @return int
     */
    public function getRelationshipType()
    {
        return $this->relationship_type;
    }

    /**
     * Generated from protobuf field <code>.lbsn.structure.Relationship.RelationshipType relationship_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRelationshipType($var)
    {
        GPBUtil::checkEnum($var, \Lbsn\Structure\Relationship_RelationshipType::class);
        $this->relationship_type = $var;

        return $this;
    }

}

